services:
  # Nginx Reverse Proxy
  nginx:
    container_name: callerai
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - callerapp
      - jambonz
    restart: unless-stopped
    networks:
      - shared_network

  # Main React Router application
  callerapp:
    container_name: callerapp
    image: oven/bun:1
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
    working_dir: /app
    command: bun run dev
    restart: unless-stopped
    networks:
      - shared_network

  # Jambonz WebSocket Service
  jambonz:
    container_name: jambonz
    image: oven/bun:1
    env_file:
      - ./services/jambonz/.env
    volumes:
      - ./services/jambonz:/app
    working_dir: /app
    command: bun run dev
    restart: unless-stopped
    networks:
      - shared_network

  # Private API Service (internal only)
  private-api:
    container_name: private-api
    image: oven/bun:1
    env_file:
      - ./services/private-api/.env
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./services/private-api:/app
    working_dir: /app
    command: bun run dev
    restart: unless-stopped
    networks:
      - shared_network

networks:
  shared_network:
    external: true
